"""loci — the genius of the place.

An ambient AI agent you summon from your zsh prompt with //. The current working
directory is its world; the Anthropic Messages API is its mind.
"""

from __future__ import annotations

# Single source of truth for the version. pyproject.toml reads this attribute
# (dynamic version), so there is no second copy to drift.
__version__ = "0.1.0"


def _commit() -> str | None:
    """Best-effort short git commit for this build, or None.

    Resolution order, fail-safe at every step (the version line must always
    render):
      1. a stamp written by install.sh — the only thing a *non-editable*
         install carries, since it copies the tree and loses the .git dir;
      2. a live `git` lookup — editable installs and plain source checkouts;
      3. nothing — installed from a wheel with no stamp.
    """
    try:
        from ._commit import COMMIT  # generated by install.sh; gitignored
        if COMMIT:
            return COMMIT
    except Exception:
        pass
    try:
        import subprocess
        from pathlib import Path
        here = Path(__file__).resolve().parent
        out = subprocess.run(
            ["git", "-C", str(here), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=2,
        )
        sha = out.stdout.strip()
        if out.returncode == 0 and sha:
            return sha
    except Exception:
        pass
    return None


def version_string() -> str:
    """Human-facing version, e.g. ``0.1.0 (e734110)`` or just ``0.1.0``."""
    commit = _commit()
    return f"{__version__} ({commit})" if commit else __version__
